# Use postgres/example user/password credentials
version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume: